services:
    prg_bundle:
        class: BurdaForward\BFPrgBundle\Service\PrgService

    prg_bundle.twig.prg_link:
        class: BurdaForward\BFPrgBundle\Twig\Extension\Prg
        tags:
            - { name: twig.extension }
        arguments: ['@twig']

    BurdaForward\BFPrgBundle\Controller\DefaultController:
        autowire: true
        autoconfigure: true
        arguments: ['@router']
        tags: [controller.service_arguments]
